### PR TITLE
fixing support for meter config statistics

### PR DESCRIPTION
**Pull request by alshabib**

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by alshabib** [comment]
Can someone have a look at this patch?

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.09.01.1644-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.09.01.1644-m.loxigen.master/abat.log
/cc

**Pull request merged**
