### PR TITLE
Add OXMs for VXLAN network identifier, inner eth dest mac, and inner eth src mac

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @rlane

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/141/
Test FAILed.

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/142/
Test PASSed.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.05.12.2022-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.05.12.2022-m.loxigen.master/abat.log
/cc

**Pull request merged**
