### PR TITLE
Add tlv for port channel hashing

### PR DESCRIPTION
**Pull request by shudongz**
Reviewer: @rlane @poolakiran @wilmo119 

Add TLVs for configuring port channel hash type, and the enhanced hash field table.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/226/

**Comment by rlane** [comment]
LGTM. @poolakiran or @wilmo119 please review as well.

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.03.03.0339-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.03.03.0339-m.loxigen.master/abat.log
/cc

**Pull request merged**
