### PR TITLE
Write revision to Maven POM on release

### LINKED ISSUE #704: Invalid pom for OpenflowJ published to Maven
The OpenflowJ pom file published to repo1.maven.org contains unresolved placeholders. For instance, the version tag reads `<version>3.6.${revision}</version>`, which causes problems for certain mvn and SBT commands. The [Maven docs](https://maven.apache.org/maven-ci-friendly.html) recommends using the plugin [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin) to generate a valid pom from a CI-friendly one before deploying.

Would it be possible to add this as a part of the Maven release process?

### PR DESCRIPTION
**Pull request by smartnetworks**
Fixes floodlight/loxigen#704.

### CODE REVIEW

**Comment by andi-bigswitch** [comment]
ok to build e295c87229a325eb122bb2e5daafa9a12ae7a72d

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-705-b2

**Comment by andi-bigswitch** [comment]
Diff to the generated POM from main branch # 604 to PR-705 looks reasonable:

```bash 
normalize-xml() { xmllint --noblanks --exc-c14n "$1" | xmllint --pretty 1 - }
diff -u <(normalize-xml openflowj-3.6.604.pom) <(normalize-xml openflowj-3.6.PR-705-20211025.154247-1.pom )
```
result: https://gist.github.com/andi-bigswitch/07d7ebdaafe2bb62bc8fa5e171e2b4c9
* Comments gone (ok)
* some benign element reordering (ok)
* build filtering removed (probably ok, only needed for build?)
* version set to `3.6.PR-705-SNAPSHOT` - nicer
* `flatten-maven-plugin` is listed (ok)

**Comment by andi-bigswitch** [comment]
Thanks for contributing this improvement, @smartnetworks !

**Pull request merged**
