### PR TITLE
Jenkinsfile

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @ronaldchl 
CC: @poolakiran 

This should unbrick  the generation of `loxigen-artifacts` (`77f31a9`). The issue there was I removed the `--quiet` parameter earlier for debugging; turns out removing the `--quiet` parameter *also* changes the exit code behavior, unless you specify `--exit-code` explicitly.

Otherwise, a couple of flags to reduce the size of the build console logs.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-598-b2

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2884//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2884//console
/cc

**Pull request closed without merging**
