### PR TITLE
openflow_input: add oxm_bsn_inner_vlan_vid.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @rlane 
CC: @sandipshah

### CODE REVIEW

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/157/
Test PASSed.

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.07.13.2149-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in loxigen/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vss1/abat/2015.07.13.2149-m.loxigen.master/abat.log
/cc

**Comment by wilmo119** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.07.13.2210-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in loxigen/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vss1/abat/2015.07.13.2210-m.loxigen.master/abat.log
/cc

**Comment by wilmo119** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.07.13.2239-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.07.13.2239-m.loxigen.master/abat.log
/cc

**Pull request merged**
