### PR TITLE
SWL-5261: TLV src_mac_cml.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @archerhungbsn @kenchiang

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-649-b1

**Comment by archerhungbsn** [comment]
look good

**Comment by kenchiang** [comment]
if we expect to use the CML settings in other places, then maybe rename the enum.
if not, that is also fine

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-649-b2

**Comment by poolakiran** [comment]
@kenchiang renamed the enum as CML is generic and can be used for dmac and other places. please take a look.

**Comment by kenchiang** [comment]
looks good; merge when ready

**Comment by poolakiran** [comment]
ACK

**Comment by poolakiran** [comment]
SELF-ACK

**Pull request merged**
