### PR TITLE
Advertise driver name and firmware version for the dpdk interfaces

### PR DESCRIPTION
**Pull request by amospaul-bsn**
Reviewer: @poolakiran @kenchiang 

CC: @3mp4y5

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-631-b1

**Comment by amospaul-bsn** [comment]
Reviewers: @kenchiang @poolakiran

**Comment by kenchiang** [comment]
looks good; thanks for making the changes.
ACK

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-631-b2

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/22165//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/22165//console
/cc

**Pull request closed without merging**
