### PR TITLE
SWL-4556 TLVs pim_packet_type, pim_dr and passive.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-618-b1

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/10437//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/10437//console
/cc

**Pull request closed without merging**
