### PR TITLE
Add tlv: push_vlan_on_egress.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @shudongz @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-572-jenkins-loxigen_pull_req_artifacts-126

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/126/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/143/

**Comment by shudongz** [comment]
What's the context of this change? Sorry, I haven't kept up with stuff.

**Comment by wilmo119** [comment]
This is another toggle for the port_config table. If it is enabled, the switch will push a dummy vlan tag to the L2GRE decapped payload, which can be overwritten at the EFP.

**Pull request merged**
