### PR TITLE
IPAddress boolean and factory methods

### PR DESCRIPTION
**Pull request by ronaldchl**
Reviewer: @andi-bigswitch @gregor-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/196/
Test PASSed.

**Comment by ronaldchl** [comment]
The `isUnspecified()` name came from:
- http://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml

  > ::/128	Unspecified Address	[RFC4291]

- http://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html

  > The Unspecified Address -- Also called anylocal or wildcard address.

  Note: Java InetAddress call its equivalent `isAnyLocalAddress()` though...

- https://docs.python.org/3/library/ipaddress.html

  > `is_unspecified`
  > True if the address is unspecified. See RFC 5735 (for IPv4) or RFC 2373 (for IPv6).

**Comment by gregor-bsn** [comment]
LGTM

**Comment by andi-bigswitch** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.10.27.2113-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.10.27.2113-m.loxigen.master/abat.log
/cc

**Pull request merged**
