### PR TITLE
Major oversight in test and typo

### PR DESCRIPTION
**Pull request by Sovietaced**
Reviewer: @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/189/
Test PASSed.

**Comment by Sovietaced** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.10.16.2118-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.10.16.2118-m.loxigen.master/abat.log
/cc

**Comment by andi-bigswitch** [comment]
Oops...

**Pull request merged**
