### PR TITLE
use githubCheckOrgAuthz

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @andi-bigswitch

Trying this out...

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-593-b5

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-593-b6

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2144//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2144//console
/cc

**Pull request closed without merging**
