### PR TITLE
New TLV types for static flag and checksum for NDP

### PR DESCRIPTION
**Pull request by adanivas**
Reviewer: @rlane 

Added TLV types for:
- Static flag to identify static endpoints in neighbor table
- icmpv6 checksum for the external router table to identify any change

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/59/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-510-jenkins-loxigen_pull_req_artifacts-53

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/53/

**Comment by rlane** [comment]
The internal wiki needs to be updated to allocate these subtypes.

**Comment by adanivas** [comment]
@rlane Added the types to the wiki.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.08.02.1651-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.08.02.1651-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
