### PR TITLE
Add tri-valued tlv for auto negotiation

### PR DESCRIPTION
**Pull request by shudongz**
Reviewer: @andi-bigswitch 
CC: @wilmo119

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/83/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-530-jenkins-loxigen_pull_req_artifacts-76

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/76/

**Comment by andi-bigswitch** [comment]
LGTM - @wilmo119 see if this looks good from your end...

**Comment by wilmo119** [comment]
LGTM

**Comment by wilmo119** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.12.06.0039-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/84/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-530-jenkins-loxigen_pull_req_artifacts-77

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/77/

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.12.06.0039-m.loxigen.master/abat.log
/cc

**Pull request merged**
