### PR TITLE
separate stage for artifact link, only on PRs

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @andi-bigswitch
CC: @ronaldchl 

Still working on a green master build...

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-596-b1

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2783//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2783//console
/cc

**Pull request closed without merging**
