### PR TITLE
Add gentable entry-priority tlv

### PR DESCRIPTION
**Pull request by harshsin**
Reviewer: @rlane 

Similar to flow-table priority.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/230/

**Comment by harshsin** [comment]
Per our offline discussion changed the tlv to be called qos_priority. And I will use the original priority tlv for table entry priority.

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/231/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.03.17.2211-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.03.17.2211-m.loxigen.master/abat.log
/cc

**Pull request merged**
