### PR TITLE
[SWL-2807] Add PFC counters to BSN port counters

### PR DESCRIPTION
**Pull request by nick-bsn**
Reviewer: @rlane 

* Added 26 port PFC counters
* Passed unit test

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/247/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/8/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.04.22.2047-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.04.22.2047-m.loxigen.master/abat.log
/cc

**Pull request merged**
