### PR TITLE
BT-7851 Add tlv to disable xmit on interface

### PR DESCRIPTION
**Pull request by shudongz**
Reviewer: @wilmo119 
CC: @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-640-b1

**Comment by wilmo119** [comment]
LGTM!

**Comment by wilmo119** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/35284//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/35284//console
/cc

**Pull request closed without merging**
