### PR TITLE
Added Nicira(OpenVSwitch) ct,nat and ct_clear actions

### PR DESCRIPTION
**Pull request by JackSunshine**
Support ovs OVS NAT and connection tracking action, it already tested base on ONOS

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by rizard** [comment]
LGTM. We have observed the same NXMs with newer OVS's in Floodlight OSS.

CC: @andi-bigswitch in case you want to peek before merge

**Comment by andi-bigswitch** [comment]
LGTM.

**Comment by rizard** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.05.01.2215-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in loxigen/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vss1/abat/2017.05.01.2215-m.loxigen.master/abat.log
/cc

**Comment by andi-bigswitch** [comment]
Oh; looks like we never ran the pre-merge tests on this one (@rizard, FYI - this doesn't automatically happen for PRs from external contributors; a org member needs to trigger them (after reviewing the code)).

JENKINS-RETRY
ARTIFACTS-RETRY

**Comment by rizard** [comment]
Ah, good to know. Thanks @andi-bigswitch

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/99/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/116/

**Comment by andi-bigswitch** [comment]
Looks like this currently breaks the C backend.
```
Writing locitest/src/test_common.c
Traceback (most recent call last):
  File "./loxigen.py", line 176, in <module>
    lang_module.generate(options.install_dir)
  File "/var/abat/2017.05.01.2215-m.loxigen.master/loxigen/lang_c.py", line 125, in generate
    fn(outfile, os.path.basename(name))
  File "/var/abat/2017.05.01.2215-m.loxigen.master/loxigen/c_gen/c_test_gen.py", line 471, in gen_common_test
    gen_unified_accessor_funs(out)
  File "/var/abat/2017.05.01.2215-m.loxigen.master/loxigen/c_gen/c_test_gen.py", line 1481, in gen_unified_accessor_funs
    gen_list_setup_check(out, cls, version)
  File "/var/abat/2017.05.01.2215-m.loxigen.master/loxigen/c_gen/c_test_gen.py", line 1075, in gen_list_setup_check
    if not type_maps.class_is_virtual(base_type):
  File "/var/abat/2017.05.01.2215-m.loxigen.master/loxigen/c_gen/type_maps.py", line 41, in class_is_virtual
    return loxi_globals.unified.class_by_name(cls).virtual
AttributeError: 'NoneType' object has no attribute 'virtual'
make: *** [.loxi_ts.c] Error 1
```

**Comment by JackSunshine** [comment]
hi @andi-bigswitch, rizard, Does this compilation error have anything to do with this modification？ btw, regarding loxigen, i think there is a problem here,  because nat action have several optional list structs, so openflowj have no idea how to convert the data to corresponding list field, it just put all data in list<ipv4_t>. I get ipv6 and port from list<ipv4> to resolve this problem temporarily

**Comment by andi-bigswitch** [comment]
Hi @JackSunshine,
> Does this compilation error have anything to do with this modification？ 

Yes, it looks like this change will require some adjustments in the C backend (`c_gen/`) to fully work. This happens quite frequently; the C backend is more manual in some ways than the other backends.

We will need to make those adjustments before we can merge this change... You could take a stab at that if you like,  or wait on us to look at the issue (but it may be a while before we can get to it).

If you want to look yourself:

You should be able to see the same build results if you run:
```
make check check-all
```
locally (on Linux), or if you have docker installed:
```
./docker.sh make check check-all
```

**Comment by JackSunshine** [comment]
hi @andi-bigswitch, I'd like to check the reason for compilation error, but i don't know where to start, I saw the same build result after run make check check-all, could you give me a bit hint how to debug this problem?
Thanks

**Comment by andi-bigswitch** [comment]
Hi @JackSunshine, sure, but I'm probably not the best person to give advice on the the C backend -- let's see if  @poolakiran or @kenchiang have time to take a quick glance at the error.

@poolakiran / @kenchiang any hints for @JackSunshine on how to fix the C build error introduced by this fix?

**Comment by pkonopka2** [comment]
Is someone taking care about this PR ? We also need this functionality and don't know if I should getting involved into fixing C build errors.

**Comment by andi-bigswitch** [comment]
It looks like #569 fixed the same issue (and also dealt with the C-backend problems). Do people agree this PR is redundant now, and can be closed?

**Comment by pkonopka2** [comment]
Yes right, this issue can be closed, thanks for your attention !

**Comment by andi-bigswitch** [comment]
Closing since nobody objected...

**Pull request closed without merging**
