### PR TITLE
BSC-9320 making LENGTH field public from IPv6Address class

### PR DESCRIPTION
**Pull request by premsharma1**
Reviewer: @ronaldchl 

Making the field LENGTH public so that could be made accessible to user modules outside the class.

### CODE REVIEW

**Comment by ronaldchl** [comment]
LGTM
Thanks! Let's see if @andi-bigswitch is OK with having 2 constants in bytes and bits before merging.

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/48/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-498-jenkins-loxigen_pull_req_artifacts-43

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/43/

**Comment by andi-bigswitch** [comment]
Hm, I would actually stick with just one LENGTH field and have that in bytes; I think that's the standard that we use across loxigen (also in the autogenerated code).

**Comment by ronaldchl** [comment]
Sure, I'm OK with that.

**Comment by premsharma1** [comment]
keeping a single change of making the field public only.

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/49/

**Comment by andi-bigswitch** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.06.23.2140-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-498-jenkins-loxigen_pull_req_artifacts-44

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/44/

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.06.23.2140-m.loxigen.master/abat.log
/cc

**Pull request merged**
