### PR TITLE
LOXI79: Deprecate MacAddress.NONE and introduce MacAddress.ZERO

### PR DESCRIPTION
**Pull request by Sovietaced**
Reviewer: @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/95/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-539-jenkins-loxigen_pull_req_artifacts-88

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/88/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/96/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-539-jenkins-loxigen_pull_req_artifacts-89

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/89/

**Comment by andi-bigswitch** [comment]
Hm; so the reason I haven't gotten back to you about this one is I think we have those NONE objects pretty frequently in those value classes; need to think about whether it makes sense to change just MacAddress (and then, if we do want to rename all of them, we probably should send out a msg to floodlight-dev about that change)

**Comment by andi-bigswitch** [comment]
Let's look at this in the context of refactoring overall NULL -> ZERO.

**Pull request closed without merging**
