### PR TITLE
Vxlan bum

### PR DESCRIPTION
**Pull request by archerhungbsn**
Reviewer: @nick-bsn

### CODE REVIEW

**Comment by nick-bsn** [comment]
Add @kenchiang and @poolakiran

**Comment by nick-bsn** [comment]
LGTM

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-632-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-632-b2

**Comment by nick-bsn** [comment]
LGTM. Thanks a lot for helping the gentables!

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-632-b3

**Pull request merged**
