### PR TITLE
Update Maven Dependencies

### PR DESCRIPTION
**Pull request by Sovietaced**
Reviewer: @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/92/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-538-jenkins-loxigen_pull_req_artifacts-85

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/85/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/93/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-538-jenkins-loxigen_pull_req_artifacts-86

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/86/

**Comment by andi-bigswitch** [comment]
Hm; actually Guava 21/Java 8 may actually a breaking change for people in the OSS community... 

It would be good to announce that change in advance.

In the mean time, let's keep the build here with Guava 20 / Java 7. Guava 22 is going to have a Java-6/7 compatible version as well...

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/94/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-538-jenkins-loxigen_pull_req_artifacts-87

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/87/

**Comment by andi-bigswitch** [comment]
Thanks Jason!

ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.02.08.0008-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.02.08.0008-m.loxigen.master/abat.log
/cc

**Pull request merged**
