### PR TITLE
Fix malformed javadoc

### PR DESCRIPTION
**Pull request by Kjwon15**
Fix literal characters, html tags, and malformed usages.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by Kjwon15** [comment]
Don't merge yet. I'll check more.

**Comment by Kjwon15** [comment]
OK. it seems fine.

**Comment by Sovietaced** [comment]
@rlane can I take care of this?

**Comment by Sovietaced** [comment]
Looks OK to me.

**Pull request merged**
