### PR TITLE
SWL-4353 Directed Broadcast instruction.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-578-jenkins-loxigen_pull_req_artifacts-140

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/140/

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/152/

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2018.02.12.1832-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2018.02.12.1832-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
