### PR TITLE
Update README.MD for versions 1.4.1 and 1.5.1

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @rlane  @rizard 

Trivial update for the README...

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/15/

**Comment by rizard** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.05.05.1925-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.05.05.1925-m.loxigen.master/abat.log
/cc

**Pull request merged**
