### PR TITLE
Add TLV and enums for UDF capabilities.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @kenchiang @shudongz

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-623-b1

**Comment by kenchiang** [comment]
i gather that this is for reporting to the controller that UDF can be programmed in 4 blocks of 4 bytes, or 8 blocks of 2 bytes.  maybe also add a "OFP_BSN_UDF_NONE = 0" value ?

**Comment by wilmo119** [comment]
@kenchiang I don't see a 0x0 defined for other bitmasks in loxigen, so I'm not sure I should start one.

**Comment by kenchiang** [comment]
sorry, i confused myself and forgot that this was a set of bitfields

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-623-b2

**Comment by wilmo119** [comment]
SELF-ACK

**Comment by wilmo119** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/13486//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/13486//console
/cc

**Pull request closed without merging**
