### PR TITLE
SWLVX-30: adding digest algorithm tlv to loxigen

### PR DESCRIPTION
**Pull request by premsharma1**
This is to add a digest algorithm tlv to loxigen.

Reviewer: @poolakiran

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-567-jenkins-loxigen_pull_req_artifacts-120

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/120/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/137/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-567-jenkins-loxigen_pull_req_artifacts-121

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/121/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/138/

**Comment by poolakiran** [comment]
Please update your TLV at https://bigswitch.atlassian.net/wiki/spaces/CORP/pages/15073513/OpenFlow+Extensions#OpenFlowExtensions-TLVExtensions

**Comment by premsharma1** [comment]
The wiki updated.

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.09.23.0043-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.09.23.0043-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
