### PR TITLE
openflow_input: add bsn_lua extension

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin

IVS supports running sandboxed Lua code as the forwarding pipeline. This 
extension allows the controller to upload the Lua code. It replaces a gentable 
used for this purpose, which didn't support atomic code changes or chunks 
larger than 64K.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.bigswitch.com//job/loxigen_pull_req/118/
Test PASSed.

**Comment by harshsin** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.01.03.0355-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.01.03.0355-m.loxigen.master/abat.log
/cc

**Pull request merged**
