### PR TITLE
SWL-3735 breakout bsn port description property.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang @Sovietaced @skini-bsn

### CODE REVIEW

**Comment by kenchiang** [comment]
LGTM
thanks for taking care of this

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-553-jenkins-loxigen_pull_req_artifacts-105

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/105/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/122/

**Comment by poolakiran** [comment]
ACK

**Comment by poolakiran** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.05.03.0325-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.05.03.0325-m.loxigen.master/abat.log
/cc

**Pull request merged**
