### PR TITLE
SWL-3343 hash_algorithm TLV.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang 
CC: @meiyangbigswitch @shudongz 

Controller can tell switch about what hash algorithm to be
used for LAG/ECMP member selection.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/97/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-540-jenkins-loxigen_pull_req_artifacts-90

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/90/

**Comment by kenchiang** [comment]
LGTM

**Comment by poolakiran** [comment]
ACK

**Comment by poolakiran** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.02.10.1925-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.02.10.1925-m.loxigen.master/abat.log
/cc

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/98/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-540-jenkins-loxigen_pull_req_artifacts-91

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/91/

**Pull request merged**
