### PR TITLE
BSC-10447 of_port_desc_prop_bsn_ethtool; return get-module data

### PR DESCRIPTION
**Pull request by 3mp4y5**
Reviewer: @poolakiran 

CC: @amospaul-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-603-b1

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/3463//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/3463//console
/cc

**Pull request closed without merging**
