### PR TITLE
In ports 512 - merge into master

### PR DESCRIPTION
**Pull request by Sovietaced**
Reviewer: @rlane

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.bigswitch.com//job/loxigen_pull_req/120/
Test PASSed.

**Comment by Sovietaced** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.01.07.0803-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.01.07.0803-m.loxigen.master/abat.log
/cc

**Pull request merged**
