### PR TITLE
Add pdua_rx_instance tlv.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @shudongz

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-562-jenkins-loxigen_pull_req_artifacts-114

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/114/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/131/

**Comment by shudongz** [comment]
LGTM
CC: @andi-bigswitch

**Comment by andi-bigswitch** [comment]
LGTM. No idea what a `pdua_rx_instance` is but I'm assuming you guys know :)

This is for BMF-6.1, correct?

**Comment by wilmo119** [comment]
Yes it's for BMF-6.1.

ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.07.10.2239-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.07.10.2239-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
