### PR TITLE
Use unsigned long comparison in IPv6Address.compareTo()

### PR DESCRIPTION
**Pull request by ronaldchl**
Reviewer: @rlane @Sovietaced

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/130/
Test PASSed.

**Comment by Sovietaced** [comment]
LGTM
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.02.07.2207-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.02.07.2207-m.loxigen.master/abat.log
/cc

**Pull request merged**
