### PR TITLE
Add auth_tokens and auth_token TLVs

### PR DESCRIPTION
**Pull request by rizard**
Reviewer: @wilmo119 @kenchiang

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-561-jenkins-loxigen_pull_req_artifacts-113

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/113/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/130/

**Comment by rizard** [comment]
Just spoke with @wilmo119. Agreed to throw this out. Will use the name TLV for both instead. Thanks @wilmo119!

**Pull request closed without merging**
