### PR TITLE
openflow_input: generate BSN messages for version 1.5

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @rlane @jnealtowns 

This auto-generated commit marks all bsn messages generated for
version 1.4 to also be generated for version 1.5

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/18/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-484-jenkins-loxigen_pull_req_artifacts-15

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/15/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.05.07.1816-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.05.07.1816-m.loxigen.master/abat.log
/cc

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/21/

**Pull request closed without merging**
