### PR TITLE
Update lua dissector name ("eth" doesn't seem to work in 2.x)

### PR DESCRIPTION
**Pull request by 3mp4y5**
Reviewer: @kenchiang 

Ken, would you take a peek?  Has anyone been using the lua dissector in recent wirewharks?

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-624-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-624-b2

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-624-b3

**Comment by kenchiang** [comment]
Updating this pull request with previous offline comments:

https://osqa-ask.wireshark.org/questions/56469/renaming-of-eth-dissector-to-eth_withoutfcs
https://osqa-ask.wireshark.org/questions/56432/how-to-find-the-ethernet-dissector

Maybe just add something to the template that generates a "works with wireshark version X.Y.Z" comment ?
And also add a fallback to getting "eth" if "eth_withoutfcs" doesn't exist ?

**Comment by 3mp4y5** [comment]
thx @kenchiang,  i'll see if i can spend a few minutes to update the PR...

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-624-b4

**Comment by kenchiang** [comment]
LGTM

**Pull request merged**
