### PR TITLE
Add use_packet_state tlv.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @rlane

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/198/
Test PASSed.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.11.06.1744-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.11.06.1744-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
