### PR TITLE
SWL-4381 fabric_port_role TLV.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/159/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-585-jenkins-loxigen_pull_req_artifacts-147

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/147/

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/969//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/969//console
/cc

**Pull request closed without merging**
