### PR TITLE
Add new port modes.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @poolakiran @rizard 

This is to add support for additional port modes supported on EOS.

This will require coordination between switch and controller to update the wire protocol since the enum values are shifted.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-674-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-674-b2

**Comment by poolakiran** [comment]
@wilmo119 as the port_mode is enum of uint16, you can append the new modes at the end of the existing list so that the wire protocol is intact and also backward compatible.

**Comment by poolakiran** [comment]
LGTM

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-674-b3

**Comment by wilmo119** [comment]
SELF-ACK

**Pull request merged**
