### PR TITLE
Added max_count & free_count

### PR DESCRIPTION
**Pull request by harishraghavendra**
Reviewer: @poolakiran @harishraghavendra

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-670-b1

**Comment by kenchiang** [comment]
@harishraghavendra : heads-up -- i've reserved 209 through 213 for some service node TLVs and will be merging this shortly.  after it merges, please update the openflow extensions wiki page and your pull request

**Comment by harishraghavendra** [comment]
> @harishraghavendra : heads-up -- i've reserved 209 through 213 for some service node TLVs and will be merging this shortly. after it merges, please update the openflow extensions wiki page and your pull request

@kenchiang Thanks for heads-up. I will update accordingly.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-670-b2

**Comment by poolakiran** [comment]
@harishraghavendra please fix the merge conflicts, LGTM otherwise.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-670-b3

**Pull request merged**
