### PR TITLE
Rename pim_packet_type TLV as multicast_packet_type.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang 
CC: @adanivas @jackiesyu @chichong-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-619-b1

**Comment by kenchiang** [comment]
i wonder if we should have removed "_type" from both this and the ip_tunnel

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-619-b2

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/10914//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/10914//console
/cc

**Pull request closed without merging**
