### PR TITLE
Add of_bsn_base_error and of_bsn_error.

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @rlane 
Thanks for helping resolve the problems I was having earlier.
Opening a new pull request that supercedes #438.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/197/
Test FAILed.

**Comment by brajneesh** [comment]
JENKINS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/209/
Test PASSed.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.12.04.2047-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.12.04.2047-m.loxigen.master/abat.log
/cc

**Pull request merged**
