### PR TITLE
Update description of apply_packets/apply_bytes

### PR DESCRIPTION
**Pull request by 3mp4y5**
Reviewer: trivial

### CODE REVIEW

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.08.31.1827-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/65/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-516-jenkins-loxigen_pull_req_artifacts-59

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/59/

**Comment by 3mp4y5** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.08.31.1827-m.loxigen.master/abat.log
/cc

**Pull request merged**
