### PR TITLE
Fix OFBitMask512

### PR DESCRIPTION
**Pull request by shudongz**
Reviewer: @Sovietaced @rlane 

Bit calculation is off.

### CODE REVIEW

**Comment by Sovietaced** [comment]
@shudongz oops, my mistake. Good catch.

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/127/
Test PASSed.

**Comment by Sovietaced** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.02.02.0756-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.02.02.0756-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
