### PR TITLE
Rebuild openflowj when pre-written files' changed

### PR DESCRIPTION
**Pull request by Kjwon15**
openflowj should be rebuilt after change pre-written files.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by rlane** [comment]
ACK

Thanks!

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.02.12.2249-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.02.12.2249-m.loxigen.master/abat.log
/cc

**Pull request merged**
