### PR TITLE
Create new

### PR DESCRIPTION
**Pull request by lucky098**

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by capveg** [comment]
@lucky098 What is this patch supposed to do?  It looks like you've created a single empty file, which is not going to have any effect AFAICT.

**Comment by lucky098** [comment]
Sorry :) I just trying to clone the code. Isn't that possible?

**Comment by capveg** [comment]
What you're trying to do now is push your modification back (of a single empty file) upstream to the main repository.  I'm going to close this pull request because it doesn't seem to be what either of us wants :-)  If you're trying to clone your repository, please check out https://help.github.com/articles/fork-a-repo/ and https://guides.github.com/introduction/flow/.

**Pull request closed without merging**
