### PR TITLE
BSC-11527: sign build maven artifacts

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @ronaldchl 

This PR makes the Maven Artifacts that we upload to the Sonatype OSS repository GPG-signed. this is necessary so that we can publish "proper" release versions (as opposed to snapshots).

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-601-b1

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  no reviewer specified in pull request description


INSTRUCTIONS: Please fix your problem by

1) Make sure line below is included in pull request description (not a follow-up comment):
Reviewer: @username @username @username ...
Leave no space at beginning of line. Use real GitHub IDs as reviewers.

2) Have at least one approval in any follow-up comment. An approval is given by including a single word of "ACK" (without quotes) in a line by itself. The approval can come from any person except the requester.

Under certain situations the requester can approve his/her own change. To do that, just include a single word of "SELF-ACK" (without quotes) in a line by itself. You are trusted not to abuse it :)

Any code review approval or new comment including the magic line of "R_E_T_R_Y" (Remove the underscores) will cause abat to automatically try to merge your code again.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-601-b2

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-601-b4

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-601-b5

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2981//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/2981//console
/cc

**Pull request closed without merging**
