### PR TITLE
SWL-4353 BSN TLV flood.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/153/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-579-jenkins-loxigen_pull_req_artifacts-141

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/141/

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/22//console

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed to merge into current code: 
GitCommandError while merging into branch master from pull request #579:
SWL-4353 BSN TLV flood. (https://github.com/floodlight/loxigen/pull/579)
  'Error when fetching: fatal: unable to fork' returned exit status 2: None


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



https://jenkins.bigswitch.com/job/loxigen-abat-automerge/22//console
/cc

**Comment by ronaldchl** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/27//console

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed to merge into current code: 
GitCommandError while merging into branch master from pull request #579:
SWL-4353 BSN TLV flood. (https://github.com/floodlight/loxigen/pull/579)
  'Error when fetching: fatal: unable to fork' returned exit status 2: None


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



https://jenkins.bigswitch.com/job/loxigen-abat-automerge/27//console
/cc

**Comment by ronaldchl** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/31//console

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed to merge into current code: 
GitCommandError while merging into branch master from pull request #579:
SWL-4353 BSN TLV flood. (https://github.com/floodlight/loxigen/pull/579)
  'Error when fetching: fatal: unable to fork' returned exit status 2: None


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



https://jenkins.bigswitch.com/job/loxigen-abat-automerge/31//console
/cc

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/38//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/38//console
/cc

**Comment by andi-bigswitch** [comment]
Hm... was this intended to go into BMF-6.3.1? We haven't bumped the maven artifact version yet, so it currently _is_ in bmf-6.3.1...

Or can we just accept it in BMF-6.3.1?

**Comment by poolakiran** [comment]
@andi-bigswitch This is for bcf-4.7, It should not impact bmf-6.3.1 either way.

**Pull request closed without merging**
