### PR TITLE
Add redundant_mgmt_reselect

### PR DESCRIPTION
**Pull request by archerhungbsn**
Reviewer: @poolakiran 
Add redundant_mgmt_reselect based on the primary_reselect in https://www.kernel.org/doc/Documentation/networking/bonding.txt

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-667-b1

**Comment by kenchiang** [comment]
From reading bonding.txt, primary_reselect can take on one of three values.
How do you plan to use this TLV?  If the primary_reselect TLV is present, to what value does that correspond?  If primary_reselect isn't present, to what value does that correspond?

**Comment by archerhungbsn** [comment]
Under current implementation, this value is 0. It means the primary master
will take the master role as long as it is up. The JIRA SWL-6072 needs a
knob to enable and disable such preempt feature. Adding the TLV as the knob.

**Comment by kenchiang** [comment]
So primary_reselect can take on one of three values, but you have a TLV whose presence or absence can only represent two values.  You have mentioned that "always" is the default.  What other value will be represented and used?  Does it make sense to add a value field to this TLV?

**Comment by archerhungbsn** [comment]
I am planning to take value 0 and 2 only.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-667-b2

**Comment by kenchiang** [comment]
lgtm; merge when ready

**Pull request merged**
