### PR TITLE
Update copyright year in file bsn_tlv.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @ronaldchl

### CODE REVIEW

**Comment by ronaldchl** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/219//console

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/154/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-581-jenkins-loxigen_pull_req_artifacts-142

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/142/

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/219//console
/cc

**Pull request closed without merging**
