### PR TITLE
[BCF-11980] Add a new TLV lossless to designate a PFC queue

### PR DESCRIPTION
**Pull request by nick-bsn**
Reviewer: @poolakiran 

* Add a new TLV lossless for the static PFC feature

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-645-b1

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/38258//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/38258//console
/cc

**Pull request closed without merging**
