### PR TITLE
Bump artifact version to 3.5.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: trivial
CC: @wilmo119 @Sovietaced 

Bump to 3.5.0-SNAPSHOT for new development iteration.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-576-jenkins-loxigen_pull_req_artifacts-138

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/138/

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/150/

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2018.01.30.2210-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2018.01.30.2210-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
