### PR TITLE
push-artifacts: support new branches

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @JanStrauss 

Jan this is the equivalent of the appliance-artifacts for loxigen. This was failing earlier when run for a branch for which the destination doesn't have an equivalent branch yet.

The strategy taken here is to 
1. list all the commit hashes of the current branch for the source repository (i.e., loxigen)
2. then step through the commit history of the master branch on the target repo (loxigen-artifact) towards the root, and try to find a commit whose `loxi-revision` is contained in (1)
3. then create a new new branch at that position.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-639-b3

**Comment by andi-bigswitch** [comment]
Friendly nudge @JanStrauss

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-639-b4

**Comment by sdmodi** [comment]
@andi-bigswitch would you please merge this and the fix for LOXI-82 soon? This is the last issue open for BCF-4.7.4. Once we do this we will have a final image that can be verified and posted.

**Pull request merged**
