### PR TITLE
Support bsn_l2_cache_hit tlv in 1.4.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @rlane

### CODE REVIEW

**Comment by wilmo119** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.02.18.0116-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/221/

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.02.18.0116-m.loxigen.master/abat.log
/cc

**Pull request merged**
