### PR TITLE
ACTSET_OUTPUT OXM should be type OFPort, not TransportPort

### PR DESCRIPTION
**Pull request by rizard**
Reviewer: @andi-bigswitch @rlane

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/24/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-487-jenkins-loxigen_pull_req_artifacts-19

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/19/

**Comment by andi-bigswitch** [comment]
From the openflow spec:
>> Egress port from action set.

Definitely an `OFPort`, not `transport port`.

LGTM

**Comment by andi-bigswitch** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.05.14.1909-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.05.14.1909-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
