### PR TITLE
Add TLV lr-all-enabled.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @poolakiran 
CC: @jnealtowns

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-621-b1

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/12529//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/12529//console
/cc

**Pull request closed without merging**
