### PR TITLE
LOXI-84: enforce maximum OF message length while writing to buffer

### PR DESCRIPTION
**Pull request by andi-bigswitch**
CC: @chichong-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-656-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-656-b2

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-656-b3

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Pull request merged**
