### PR TITLE
Add DHCPV6 pktin reason

### PR DESCRIPTION
**Pull request by archerhungbsn**
Reviewer: @poolakiran @harishraghavendra 
Add DHCPV6 pktin reason

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-687-b1

**Comment by poolakiran** [comment]
@archerhungbsn Did you consider using DHCP reason and use eth_type to differentiate DHCPV4/6? IMHO we could use the same cpu queue for DHCPV6 packets as well.

**Comment by archerhungbsn** [comment]
We can use the {DHCP + Eth_type} to differentiate the v4 DHCP and V6 DHCP. The reason bitmap doesn't have the Eth_type. The receiver has to look into the packets to get the eth_type. Giving the different reason bits will be easier for receivers to process/dispatch the packets.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-687-b2

**Comment by poolakiran** [comment]
OK @archerhungbsn, LGTM

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-687-b3

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-687-b4

**Pull request merged**
