### PR TITLE
BSC-8167: java/pom.xml: update mvn 0.10.0-SNAPSHOT, update libraries

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @Sovietaced 

FYI: @ronaldchl

This PR updates the core libraries included in openflowj to more recent version (necessary for SSL Suppot w/netty).

It also remove the LengthCountingPseudoChannelBuffer. It was not
used and did not work with the updated version of netty.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/165/
Test PASSed.

**Comment by Sovietaced** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.08.24.1515-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.08.24.1515-m.loxigen.master/abat.log
/cc

**Pull request merged**
