### PR TITLE
[SWL-6518] ccf_feature TLV.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @harishraghavendra
CC: @zhaodong-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-697-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-697-b2

**Review by harishraghavendra — APPROVED** [review]
LGTM, thanks

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-697-b3

**Pull request merged**
