### PR TITLE
New TLVs ingress_port_group_id, ingress_port_group_id.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang 
CC: @nsong

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/68/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-519-jenkins-loxigen_pull_req_artifacts-62

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/62/

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.09.15.1944-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.09.15.1944-m.loxigen.master/abat.log
/cc

**Pull request merged**
