### PR TITLE
BVS-7800 use_peer_when_empty TLV.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang @skini-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-552-jenkins-loxigen_pull_req_artifacts-103

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/103/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/120/

**Comment by kenchiang** [comment]
ACK
you may need to update to pull in ryan's changes.

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.05.02.2025-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.05.02.2025-m.loxigen.master/abat.log
/cc

**Pull request merged**
