### PR TITLE
Add bsn_hash_select instruction.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @rlane 
CC: @nick-bsn @sandipshah

This is for supporting a hash select action in a flow table entry.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/61/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-513-jenkins-loxigen_pull_req_artifacts-55

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/55/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.08.25.2052-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.08.25.2052-m.loxigen.master/abat.log
/cc

**Pull request merged**
