### PR TITLE
Add metadata and packet_field TLVs

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @3mp4y5 @rizard @AnuragChowdhary-bsn

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-686-b1

**Comment by rizard** [comment]
LGTM. Thanks @kenchiang!

**Comment by AnuragChowdhary-bsn** [comment]
@rizard @kenchiang If we take example of dedup, what values you expect to be there. Lets say SN receives 3 tags, out of which outer ones are policy tag and filter tag. We do not want dedup to consider filter tag, but consider policy tag for hashing.   

I am just trying to connect some dots about how the tlv will look like in few cases.

**Review by 3mp4y5 — APPROVED** [review]
LGTM

thanks for working on this

**Review by AnuragChowdhary-bsn — APPROVED** [review]

**Pull request merged**
