### PR TITLE
Add of_bsn_table_full_error.

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @andi-bigswitch 

A trial balloon -- let me know if you think there is a better way to do this.  Thanks.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/86/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-532-jenkins-loxigen_pull_req_artifacts-79

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/79/

**Comment by kenchiang** [comment]
Superseded by https://github.com/floodlight/loxigen/pull/533

**Pull request closed without merging**
