### PR TITLE
In port 512

### PR DESCRIPTION
**Pull request by Sovietaced**
Reviewer: @rlane

### CODE REVIEW

**Comment by carlroth** [comment]
I doubt I'm the right person to review this, I've never worked on loxigen.

**Comment by Sovietaced** [comment]
Sorry @carlroth. Meant to tag @rlane

**Comment by Sovietaced** [comment]
ping @rlane

**Comment by Sovietaced** [comment]
JENKINS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.bigswitch.com//job/loxigen_pull_req/119/
Test PASSed.

**Comment by Sovietaced** [comment]
@ronaldchl Is ABAT acting up? Been sitting on this A_C_K for 2 hours now. It looks like its working fine for internal repos.

**Comment by Sovietaced** [comment]
ABAT isn't setup to handle this branch. So manually merging this and opening a PR on master.

**Pull request merged**
