### PR TITLE
Add tlv to describe lag config option flags.

### PR DESCRIPTION
**Pull request by wilmo119**
Reviewer: @andi-bigswitch @shudongz @kenchiang 
CC: @sandipshah

Suggestions on better names are welcome (e.g lag_config_flags, lag_flags, lag_config, ...)

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-563-jenkins-loxigen_pull_req_artifacts-115

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/115/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/132/

**Comment by kenchiang** [comment]
lgtm

**Comment by shudongz** [comment]
Looks good.

**Comment by wilmo119** [comment]
ok thanks.

SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.07.12.0039-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.07.12.0039-m.loxigen.master/abat.log
/cc

**Pull request closed without merging**
