### PR TITLE
add gencmd extension and of_bsn_tlv_vlan_mac_list

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @poolakiran

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/222/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/223/

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.02.18.2144-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.02.18.2144-m.loxigen.master/abat.log
/cc

**Pull request merged**
