### PR TITLE
SWL-4474 uint32 TLV.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @kenchiang 
CC: @chichong-bsn

### CODE REVIEW

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/6247//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/6247//console
/cc

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-612-b1

**Pull request closed without merging**
