### PR TITLE
recursive TLV fixes

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @wilmo119

The of_bsn_tlv_bucket class exposed some issues in the C and Python backends
due to its recursive definition.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/124/
Test PASSed.

**Comment by wilmo119** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.01.22.2036-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.01.22.2036-m.loxigen.master/abat.log
/cc

**Pull request merged**
