### PR TITLE
Add BFD_REMOTE_ADMINDOWN state for bfd async event

### PR DESCRIPTION
**Pull request by archerhungbsn**
Reviewer: @poolakiran

### CODE REVIEW

**Comment by poolakiran** [comment]
As we discussed, please append the new entry at the end for backward compatibility and self-ack.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-626-b1

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-626-b2

**Comment by poolakiran** [comment]
ACK

**Comment by poolakiran** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/15819//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/15819//console
/cc

**Pull request closed without merging**
