### PR TITLE
add vlan_pcp tlv

### PR DESCRIPTION
**Pull request by harshsin**
Reviewer: @rlane

### CODE REVIEW

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/135/
Test PASSed.

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.04.02.1950-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.04.02.1950-m.loxigen.master/abat.log
/cc

**Pull request merged**
