### PR TITLE
Add OFP_BSN_PKTIN_FLAG_ANALYTICS

### PR DESCRIPTION
**Pull request by shudongz**
Reviewer: @rlane 
CC: @wilmo119 

When the flag is set, the switch agent sends the packet in to analytics VM instead of the controller. This is similar to OFP_BSN_PKTIN_FLAG_SFLOW.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-499-jenkins-loxigen_pull_req_artifacts-45

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/45/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/50/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.07.02.1608-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.07.02.1608-m.loxigen.master/abat.log
/cc

**Pull request merged**
