### PR TITLE
LOXI-85: document behavior of OFMessageReader

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @weifanfu-bsn @andre-bigswitch @ronaldchl

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-660-b1

**Comment by andi-bigswitch** [comment]
CC: @WeifanFu-bsn @Andre-Bigswitch (FYI) not sure if you got the earlier notification since you weren't in the org previously.

Thanks @ronaldchl !

SELF-ACK

**Comment by WeifanFu-bsn** [comment]
@andi-bigswitch  I got the earlier notification. No need to add the CC :)

**Comment by andi-bigswitch** [comment]
Hm, the abat bot doesn't seem to like me somehow.

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/46660//console

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed to merge into current code: 
AttributeError while merging into branch master from pull request #660:
LOXI-85: document behavior of OFMessageReader (https://github.com/floodlight/loxigen/pull/660)
  'GitCmdObjectDB' object has no attribute 'update_cache'


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



https://jenkins.bigswitch.com/job/loxigen-abat-automerge/46660//console
/cc

**Pull request merged**
