### PR TITLE
BSC-11527 rework build: add Jenkinsfile, use MVN CI friendly versioning

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @ronaldchl 

This reworks the build process for Loxigen to run entirely in a custom
docker container, and with the Jenkins native docker agent support.

It also consolidates all of the build jobs for loxigen in a single
Jenkinsfile.

Lastly, it changes the versioning model for the MVN artificats deployed.

Master builds now become release (as opposed to SNAPSHOT) builds; with
the patch version taken from the build number.

This means that dependent projects can reference a stable release
version that won't ever change; we don't need to manually bump the MVN
version.

### CODE REVIEW

**Comment by bsn-bot3** [comment]
Build finished.

**Comment by bsn-bot3** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/189/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-589-b1

**Comment by andi-bigswitch** [comment]
A'ight let's give this a try...

SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  https://jenkins.bigswitch.com/job/loxigen-abat-automerge/1807//console

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
https://jenkins.bigswitch.com/job/loxigen-abat-automerge/1807//console
/cc

**Pull request closed without merging**
