### PR TITLE
bump netty version

### PR DESCRIPTION
**Pull request by YutaHiguchi-bsn**
Bumping netty version to latest release version 4.1.42.Final

https://netty.io/news/2019/09/25/4-1-42-Final.html

### CODE REVIEW

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-657-b1

**Comment by andi-bigswitch** [comment]
Do we expect any behavior change from this version bump? At least superficially it looks small (patch version 4.1.17 -> 39)?

**Comment by YutaHiguchi-bsn** [comment]
Looking through their release notes: https://netty.io/news/

It say there that it's a bugfix & performance release, 
but there seems to be active development going on around http2, 
so in theory there can be risks that it had side-effect in other places how it behaves.

This is not blocking anything, 
so we can either just hold merging this, 
or merge this, but put a hold on controller side, not start using new openflowj version yet.

**Comment by andi-bigswitch** [comment]
> This is not blocking anything, so we can either just hold merging this, or merge this, but put a hold on controller side, not start using new openflowj version yet.

Sometimes required fixes or changes to openflowj come in late in the release so I wouldn't want to block the consumption of newer openflowj; once we merge it here, we should also consume it.

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/PR-657-b2

**Comment by YutaHiguchi-bsn** [comment]
SELF-ACK

**Pull request merged**
