### PR TITLE
java/pom.xml: bump version to 3.2.0-SNAPSHOT for new dev cycle

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @Sovietaced 

Bumping OpenFlowJ version for the new dev cycle...

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_docker/89/

**Comment by bsn-abat** [comment]
Find artifact changes from this pull request at https://github.com/floodlight/loxigen-artifacts/tree/pr-535-jenkins-loxigen_pull_req_artifacts-82

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/82/

**Comment by andi-bigswitch** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2017.02.07.1734-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2017.02.07.1734-m.loxigen.master/abat.log
/cc

**Pull request merged**
