### PR TITLE
syntax for field length members

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @andi-bigswitch

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/239/

**Comment by andi-bigswitch** [comment]
LGTM - thanks for improving this!

ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.04.20.2107-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.04.20.2107-m.loxigen.master/abat.log
/cc

**Pull request merged**
