### PR TITLE
Added new TLVs for GRE tunnel gen table

### PR DESCRIPTION
**Pull request by vaterlaus**
Reviewer: @shudongz @wilmo119 

I also updated the wiki page (https://bigswitch.atlassian.net/wiki/display/BSC/Controller-Switch+Interaction+Enhancements) with some more details.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/232/

**Comment by shudongz** [comment]
Need to update TLV number reservation on wiki page: https://bigswitch.atlassian.net/wiki/display/CORP/OpenFlow+Extensions

**Comment by shudongz** [comment]
Look good to me. @wilmo119 Can you verify that using other TLVs to infer the tunnel direction is OK from the switch processing perspective?

**Comment by wilmo119** [comment]
LGTM.

ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.03.22.0043-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.03.22.0043-m.loxigen.master/abat.log
/cc

**Pull request merged**
