### PR TITLE
push-artifacts: add support to specify new target branch to be created

### PR DESCRIPTION
**Pull request by andi-bigswitch**
Reviewer: @rlane 

This is intended so we can easily inspect the artifact differences of
pull requests.

Jenkins integration pending.

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/240/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/1/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/2/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/3/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/241/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/4/

**Comment by andi-bigswitch** [comment]
ARTIFACTS-RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req/242/

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com/job/loxigen_pull_req_artifacts/5/

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2016.04.20.2317-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2016.04.20.2317-m.loxigen.master/abat.log
/cc

**Pull request merged**
