### PR TITLE
IGMP and PIM packet-in reasons.

### PR DESCRIPTION
**Pull request by poolakiran**
Reviewer: @rlane 
CC: @kenchiang

### CODE REVIEW

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/loxigen_pull_req/185/
Test PASSed.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vss1/abat/2015.10.08.2356-m.loxigen.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vss1/abat/2015.10.08.2356-m.loxigen.master/abat.log
/cc

**Pull request merged**
